version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: frontend
    stdin_open: true
    volumes:
      - ./:/var/www/html/dndnew
      - /var/www/html/dndnew/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`dndnew.hu`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    ports:
      - 5173:5173
    networks:
      - traefik-public
    command: npm run dev

networks:
  traefik-public:
    external: true
